# Generated by Django 2.1.2 on 2018-12-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_auto_20181203_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_cli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='add_OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField(max_length=50)),
                ('hora_ini', models.CharField(max_length=50)),
                ('hora_ter', models.CharField(max_length=50)),
                ('id_ascen', models.CharField(max_length=5)),
                ('modelo', models.CharField(max_length=10)),
                ('fallas', models.CharField(max_length=100)),
                ('reparacion', models.CharField(max_length=100)),
                ('pieza_cam', models.CharField(max_length=100)),
                ('nom_trab', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.AddField(
            model_name='add_cli',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitioweb.Tecnico'),
        ),
    ]
