# Generated by Django 2.1.2 on 2018-12-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0005_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
