# Generated by Django 2.1.2 on 2018-12-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0006_auto_20181213_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='correo',
        ),
    ]
